[package]
name = "proc-macro-api"
version = "0.1.0"
edition = "2024"
description = "A macro helping with exporting APIs in a proc_macro library crate."
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["proc_macro", "api", "export", "submodule"]

[dependencies]

[features]
default = ["no_shadow"]
no_override = []
no_shadow = []

[[example]]
name = "tests"
crate-type = ["proc-macro"]
